### ISSUE TITLE
wrong country for PH

### ISSUE THREAD

**Issue by elgaard** [opening-hours/opening_hours.js#118] opened 2015-10-21 02:07 UTC
When checking e.g.
https://www.openstreetmap.org/node/280957608

witch http://openingh.openstreetmap.de/

I get the error:

==
An error occurred during evaluation of the value "Mo-Sa 11:00-23:00; Su,PH 11:00-21:00". Please file a bug report here: https://github.com/ypid/opening_hours.js/issues?state=open. There are no holidays PH defined for country se. You can also add them: __repository_url__
==

But the node is in Denmark, not Sweden.

It could be a problem with the data.
How is the county determined?

**Comment by ypid** [comment] 2015-10-22 22:20
Nominitim returns the correct country. https://nominatim.openstreetmap.org/reverse?format=json&lat=55.68857&lon=12.52567&zoom=18&addressdetails=1

Not yet sure where the problem is.

**Comment by dex2000** [comment] 2016-01-01 23:22
cannot reproduce here:

http://openingh.openstreetmap.de/?zoom=18&lat=55.68857&lon=12.5251&layers=B0T&filter=none&tags=opening_hours

nor here:
http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2010%3A00-20%3A00%3B%20PH%20off&DATE=1450999080000&lat=48.7769&lon=9.1844&mode=0#

but found another bug on the english-tab (with ua-language=english or danish or swedish (or german)):
    Facility is now closed, comment: "1. Weihnachtstag"

**Comment by ypid** [comment] 2016-01-02 14:09
This might be related to https://github.com/opening-hours/opening_hours_map/issues/34 so I am closing it here. When you open http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Sa%2011%3A00-23%3A00%3B%20Su%2CPH%2011%3A00-21%3A00&lat=55.6885488&lon=12.525126 it also does reverse geocoding and shows you the result (dk, which is correct). @elgaard Did you start in Sweden and then moved to Denmark in the map?

@dex2000 You are refering to "Facility is now closed, comment: "1. Weihnachtstag"
but will close tomorrow, 26 December, in 8 hours and 55 minutes."? [here](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2010%3A00-20%3A00%3B%20PH%20off&DATE=1451052300000&lat=48.7769&lon=9.1844&mode=0)? I agree that this should be fixed. The course for this problem is that different comments are returned by the PH code and this it is evaluated as additional events. I think the best fix to make this clear is to just add the different comment to the second line. Will do that now.

**Comment by ypid** [comment] 2016-01-02 14:46
@dex2000 Did you mean that? If not, feel free to open a new issue.

**Closed by ypid** 2016-01-02 14:46 UTC
Labels: question

**Comment by dex2000** [comment] 2016-01-02 15:45
dont understand your answer complete.
i meant the german word "Weihnachtstag" in different Browser-UAs and chosen different languages on the evaluation tool.

Ich habe verschiedene UAs im Browser getestet und zusätzlich verschiedene Sprachen am tool eingestellt, ich bekomme immer "Weihnachtstag" statt des entsprechenden Äquivalents.

**Comment by ypid** [comment] 2016-01-02 16:15
@dex2000 Ah right. Translating PH names is currently not supported. Showing those names as comment in the first place was done by me because I thought why not in case no other comment was specified. I don’t think that it is a good idea to want to translate PH/SH names because they might be only known in the country/local culture anyway and might not have words in other languages. On the other hand, it would be not that difficult to do that so I opened an issue for that #138.
