### ISSUE TITLE
Time after midnight

### ISSUE THREAD

**Issue by HolgerJeromin** [opening-hours/opening_hours.js#87] opened 2015-06-08 14:16 UTC
If the time is defined after midnight, the overwriting rule makes mistakes:
[`Mo-Su,PH 15:00-03:00; easter -2 days 15:00-24:00`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Su%2CPH%2015%3A00-03%3A00%3B%20easter%20-2%20days%2015%3A00-24%3A00&DATE=1427896080000&lat=50.7680669&lon=6.080150000000001&mode=0)
1: Why is the sunday bar graph not aligned to the other days?
2: Why is the amenity open on the saturday after the good friday :-)

**Comment by ypid** [comment] 2015-06-08 19:15
Those mistakes are well defined (see [specification](https://wiki.openstreetmap.org/w/index.php?title=Key:opening_hours/specification#explain:time_domain)) and are the only way to be consistend:

1. [Daylight saving](https://de.wikipedia.org/wiki/Sommerzeit#Deutschland)
2. Pardon? There is no `off` rule being used and `Mo-Su,PH 15:00-03:00` applies for all days. The rule `easter -2 days 15:00-24:00` overwrites the frieday complatly and changes the opening time to 15:00-24:00.
You mean the time range `Sa 00:00-03:00`? You are right, that is a bit strange but again, this has been done to be consistand and is covered by the specification.

Please rewrite as: [`Mo-Su,PH 15:00-03:00; easter -2 days 15:00-24:00; easter -1 day 00:00-03:00 off`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Su%2CPH%2015%3A00-03%3A00%3B%20easter%20-2%20days%2015%3A00-24%3A00%3B%20easter%20-1%20day%2000%3A00-03%3A00%20off&DATE=1427896080000&lat=50.7680669&lon=6.080150000000001&mode=0)

Was this helpful?

**Comment by HolgerJeromin** [comment] 2015-06-09 06:56
Oh, i missed the daylight saving. Thanks!

I meant the Sa night, yes. I thought a time 15:00-03:00 is "hanging" on the start day and could be overwritten by the shorter 15:00-24:00 rule from this day.

**Comment by ypid** [comment] 2015-06-09 17:38
I guess it would be nice if this library could be smart enough to detect those special cases. This is certainly possible but pretty advanced as well. I think it makes sense to discuss if we should change this behavior.
i also almost overlooked the current behavior: http://forum.openstreetmap.org/viewtopic.php?pid=500424#p500424
That said, there are currently other open issues which should be solved first :) If you know how to implement this, please go ahead :smile:

**Comment by mkyral** [comment] 2016-02-24 08:39
Hi, I just testing parsing of oh for our "active layer" and I'm also affected by this. In Czech republic, in bigger cities are often pubs open over the midnight.

E.g.: We-Th 17:00-01:00; Fr-Sa 17:00-04:00 is not parsed correctly. 
On Wednesday I got opening hours for tomorrow ('Zítra') 17:00 - 24:00, but I should get 17:00 - 01:00 - the same as for today ('Dnes')

![oh02](https://cloud.githubusercontent.com/assets/155542/13279259/b964e31a-dad6-11e5-9b6c-41509c7b2cec.png)

**Comment by mkyral** [comment] 2016-02-24 08:51
It seems like last day in interval is cutted when there is next interval:

This: `We-Sa 20:00-06:00` is parsed correcty.
And this: `We-Sa 20:00-06:00;Su-Tu 20:00-01:00` not. Sa value is cutted on midnight.

**Comment by dex2000** [comment] 2016-02-24 09:44
Uuh, strange. 
Workaround: Su-Tu 20:00-01:00; We-Sa 20:00-06:00

**Comment by mkyral** [comment] 2016-02-24 10:11
Well, it works in this case, But not for this: `Mo-Th 17:00-01:00;Fr-Su 17:00-04:00`. Depends on order, Thursday or Sunday is cutted.

**Comment by dex2000** [comment] 2016-02-24 10:55
of course its a bug, but other workaround should be to use Komma-separated values.

**Comment by mkyral** [comment] 2016-02-24 11:57
Well I can't update all opening hours across whole Czech Republic as this is the planned area of usage ;-) 

Maybe evening I'll look on it.

**Comment by ypid** [comment] 2016-02-24 22:22
I would suggest the retagging nevertheless. Something like this `We-Sa 20:00-06:00, Su-Tu 20:00-01:00` should get you the result you are looking for. I would not call it a bug, it works as advertised :wink:

**Comment by dex2000** [comment] 2016-02-24 22:48
ypid: you have an idea for an overpass-question to find midnight-overlapping times for check manually?
deutsch: ich hab heute einige wenige Öffnungszeiten in meiner Nähe korrigiert, die in das "kaputte" Schema passen. Ich bin nun auf der Suche nach weiteren möglicherweise problematischen Einträgen deutschlandweit. 
Was ich suche: OH, die 24 Uhr überschreiten und/oder durch andere Werte per Semikolon "überschrieben" werden. Also alle Werte die 24 Uhr überschreiten.

P.s. Wie gesagt, glaube ich dass das ein Bug ist, obwohl die Auswertung inhaltlich und semantisch nicht zu beanstanden und richtig ist.

**Comment by mkyral** [comment] 2016-02-25 08:15
@ypid  Hmm, you are right. But that's really ugly. Only one small additional dot and so big [difference](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator) :-(

So I need fix it in osm.

**Comment by ypid** [comment] 2016-02-25 12:16
I understand that this means some work but it was always clearly defined as such. When we consider this issue a bug in the syntax and try to solve it we would do more harm than good. If you have a better solution please discuss this on the tagging mailing list.

@dex2000 I remember that I once wrote a query for PH stuff. You should be able to reuse this query. All the magic can be done with regular expressions [with certain limitations](https://wiki.openstreetmap.org/wiki/Talk:Key:opening_hours#Regular_expression). To do what you are looking for you can probably get started with this one: `[,-]\s*0\d[.:]\d?\d\s*;.{4}` (untested on the overpass API). Happy mapping :smile: and thanks :+1:

**Comment by mkyral** [comment] 2016-02-25 13:52
@ypid It was nothing against you. Just sigh. From my point of view it is solved.

But maybe evaluation hours tool could show some warning in such case - oh over midnight and next interval delimited by semicolon.

**Comment by ypid** [comment] 2016-02-25 14:23
@mkyral It‘s all good :wink:

That’s the reason why the issue is still open :wink:

Cheers

**Comment by dex2000** [comment] 2016-02-25 15:20
Ok, the regex dont helps me (no knowlegde about), will ask in the forum for that.

**Comment by dex2000** [comment] 2016-02-26 09:58
got an overpass-turbo-question for that:
http://overpass-turbo.eu/s/eDw (from here: http://forum.openstreetmap.org/viewtopic.php?pid=579681#p579681)
it searches for OH what contains over-midnight ranges like: "**-03:00;**"
the range goes up to 06:00

The example is for thuringia with 32 results, 6 times me was last editor, only 2 (of all 32) was "false positive", the rest wrong. Will go to fix rest of germany today.

**Comment by dex2000** [comment] 2016-02-26 16:07
Question about that: is my intention right, that on over-midnight-ranges every "off", closed and similar must be placed on the beginning the rules?

**Comment by dex2000** [comment] 2016-02-27 10:56
PH,SH and some Month/Weekly things are pain with that.
Example: _Mo-Sa 06:00-05:00; Su,PH 10:00-05:00_
Right tagging for that(?):
_Mo-Sa 06:00-05:00; Su,PH 10:00-05:00, PH Tu-Su - 1 day 06:00-05:00 [... ???]_
oO
Other examples for breaking the brain:
_Mo-Th 08:00-03:00, Fr-Sa 08:00-06:00, Su,PH 09:00-03:00
Mo-We 17:00-01:00, Th,Fr 15:00-01:00; PH off
Mo-Sa 16:00-01:00, Su 10:00-14:00, 16:00-01:00, SH 11:00+
Mo-Th 07:00-01:00; Fr-Sa 07:00-06:00; Su,PH 09:00-01:00_

**Comment by ypid** [comment] 2016-02-27 14:40
Try this value instead: `Mo-Sa 06:00-05:00, Su,PH 10:00-05:00; PH 06:00-10:00 off`. Because the closing times (05:00) are identical. The only difference for PH is that we need to cut out 06:00-10:00 for the PH. Because the `PH 06:00-10:00 off` rule does not overwrite times after midnight, the `00:00-05:00` peace of the `Mo-Sa 06:00-05:00` rule is still in effect.

The same pattern works for your other examples:

`Mo-Th 08:00-03:00, Fr-Sa 08:00-06:00, Su,PH 09:00-03:00` -> `Mo-Th 08:00-03:00, Fr-Sa 08:00-06:00, Su,PH 09:00-03:00; PH +1 day 03:00-06:00 off`

**Comment by dex2000** [comment] 2016-02-27 15:32
Ok, cutting works.
But it's not very easy to build and/or to read.

Yep, the regex is similar, but i cant not build a valid term with it myself.

**Comment by ypid** [comment] 2017-03-10 21:37
#220 includes a patch which adds a warning for this. Note the changelog of #220 for details. Also note that this check is also effected by the unfortunate #86 which causes the check to not report warnings if an `<additional_rule_separator>` is already used.

**Closed** 2017-03-19 21:11 UTC
Labels: status/spec_needed, type/enhancement, type/question
