### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by thany** [opening-hours/opening_hours.js#298] opened 2019-09-27 14:32 UTC
When I add this module to my project by just installing it like any other module, I can't import it.

Added like any other module:
```
npm i --save opening_hours
```

I'm just doing:
```typescript
import opening_hours from 'opening_hours';
```
As is the norm. Again, this works with any other module just fine.

And the complete lack of instruction on how to actually import this script into a project, leaves me guessing. So all I can do, is import it like I import any other module.

The error I'm getting is rather strange:
```
./node_modules/opening_hours/locales/core.js
Module not found: Can't resolve 'i18next-client' in 'C:\...\node_modules\opening_hours\locales'
```
So it looks like opening_hours cannot find one of its own files. I thought maybe the entry point is incorrect in your package.json, but to my surprize, there isn't any, so I think that means it assumes index.js, which doesnt exist. Doesn't explain the error though.

I also saw uglify-js in your dependencies. And another one in your devDependencies. So you're using uglify-js at runtime?? I should hope not... Again, this doesn't explain the error, but the reason I mention it, is because this indicates to me that not enough love has gone into package.json and perhaps properly modularizing it.

I sure hope it's not the main `opening_hours.js` in the project root. At 418KB, it seems *rather* large for what it is. Unless it supports tree-shaking, that is.

**Comment by thany** [comment] 2019-09-27 15:04
Turns out I have to manually install `i18next-client`:
```
npm i --save i18next-client
```
And then it'll build. Why is this module not installed automatically? It's required for a successful build, so you can't leave it optional or anything.

Now that my project builds again, my total javascript size is ballooned by about 210KB. That probably that big honkin' main file but minified. Again, why is it so big?? I can also answer my own question about tree-shaking: no.

So can you please make this module smaller? 210KB minified just to parse/display some business hours is just proposterous. If not, can you make it support tree-shaking then?

**Comment by ypid** [comment] 2019-09-27 19:58
Hi again @thany 

Let me start by saying that I don’t really appreciate your demanding tone in your comments. You know that I am doing all of this work and maintenance for free in my own spare time that I could use for other fun activities? If this project would not exist, you would be required to start from zero spending tens of thousands of money units to get to this majority. There is a lot of love in this project. But lately, I needed to step back a bit from developing. I hope to increase this again but then for the OpenStreetMap community. Please show me your involvement with OpenStreetMap and I might get over your tone.

Now to your question. It will be shorter than usual (reasoning see first paragraph):

Duplicate of: #232 
Ref: #150, #143

**Closed by ypid** 2019-09-27 19:58 UTC

**Comment by thany** [comment] 2019-09-30 10:21
I didn't think I was writing in a very demanding tone, and certainly didn't intent to convey as such. I'm sorry about that. The way that I write (and speak) is with more of an overstating tone. So 1MB of javascript becomes 1GB in my tone.

Everyone is different, and everyone speaks (and writes) in a different way. And indeed, everyone understands things in a different way. In our case your understanding and my tone did not match. But demanding is the least of what I'm doing. I hope you can understand this.

**Comment by ypid** [comment] 2019-09-30 19:10
Thanks for explaining. If you could stay objective and not mix issues like in the a bit ranty comments above we can try to work together if you want to bring this project forward and help with the issues that it definitely has. As with #299. You showed something concrete without mixing it up and I was able to reproduce and then track it as issue.
