### ISSUE TITLE
Can not install directly opening_hours as npm package

### ISSUE THREAD

**Issue by Calderis** [opening-hours/opening_hours.js#378] opened 2021-02-24 08:49 UTC
The latest release does not include latest update about school holidays so the other option to include opening_hours in a project is to directly use the github url as the version for a npm package.

```
{
  "name": "node-http-server",
  "version": "1.0.0",
  "description": "Node.js example server starter project",
  "main": "src/index.js",
  "scripts": {
    "start": "nodemon src/index.js"
  },
  "dependencies": {},
  "devDependencies": {
    "nodemon": "1.18.4",
    "opening_hours": "https://github.com/opening-hours/opening_hours.js.git"
  },
  "keywords": []
}

```
Try installing package yourself on : https://codesandbox.io/s/affectionate-bush-3lnbj?file=/package.json

But it seems that it does not work and package can not be installed properly. An error is returned : 
```
error /sandbox/node_modules/opening_hours: Command failed.
Exit code: 127
Command: husky install
Arguments:
Directory: /sandbox/node_modules/opening_hours
Output:
/bin/sh: 1: husky: not found
```

Note : At this moment, the latest public commit is : https://github.com/opening-hours/opening_hours.js/commit/a8a8b69ef41cd470a32fae642d3825be30ac930d
Note 2 : Installing husky as npm package does not solve the problem either

---
One of the latest working point (for a successfull npm package installation) is to use the `https://github.com/opening-hours/opening_hours.js.git#3eb159745cb08901367e684afd10a98dcc1cabe0` commit as package version.

But infortunately we won't have the latest change (such as future school holiday updates).

Thanks for the work !

**Comment by ypid** [comment] 2021-02-26 20:46
Thanks, this is exactly the testing I am looking for. Ref: #360

@napei Any idea what the issue with husky is?

**Comment by napei** [comment] 2021-02-27 01:13
> @napei Any idea what the issue with husky is?

Pretty sure it's because it's trying to install from a git repo. There's no built assets in the git repo, and husky is there because it hasn't been turned off during a build using `pinst` like it should. In other words, don't install npm packages from their git path, because that's not what gets shipped to npm so they won't even work anyway.

@ypid I would probably suggest deploying a `next` or `beta` build to npm given that there's possible breaking changes and it's been a while, accompanis with a major version bump. That way people can test it without it being a final release.

**Comment by ypid** [comment] 2021-03-01 20:54
Done that. But I did a mistake and published `3.6.0-beta.0` as release …

I deprecated this release but I could not unpublish it. I now published https://www.npmjs.com/package/opening_hours/v/3.6.0-beta.1 And did some simple manual test. Feel free to test this. Because of the `3.6.0-beta.0` situation, I guess `3.6.0` should be released in a few weeks.

**Comment by napei** [comment] 2021-03-04 01:47
@ypid with this, installing the latest version as a package does not include i18next-client. It probably needs to be added as a peer-dep for use with npm properly. I'll raise a PR to fix this.

**Comment by ypid** [comment] 2021-03-04 22:12
There is an issue with your test code I would say. `getReadableState` is a helper function not defined by the library, see https://github.com/opening-hours/opening_hours.js#synopsis

```js
console.log(oh.getReadableState("We're", "", oh, true));
```

It works with this also with the beta version:

```js
console.log(getReadableState("We're", "", oh, true));
```

**Comment by napei** [comment] 2021-03-05 02:05
> There is an issue with your test code I would say. `getReadableState` is a helper function not defined by the library, see https://github.com/opening-hours/opening_hours.js#synopsis
> 
> ```js
> console.log(oh.getReadableState("We're", "", oh, true));
> ```
> 
> ~It works with this also with the beta version:~
> 
> ```js
> console.log(getReadableState("We're", "", oh, true));
> ```
> 
> Edit: My mistake. You are right, `i18next-client` is needed.

My bad, I didn't pay too much attention when copying 😂

**Comment by ypid** [comment] 2021-03-05 20:10
I am closing this as duplicate of #360. I forgot that I already have an issue open for this where people might be subscribed to and waiting.

**Closed by ypid** 2021-03-05 20:10 UTC
Labels: status: duplicate
