### ISSUE TITLE
It is unclear what input fields are editable and what are not

### ISSUE THREAD

**Issue by Eiim** [opening-hours/opening_hours.js#347] opened 2020-10-25 17:05 UTC
The textboxes don't pull up the on-screen keyboard on my phone, making it impossible to type in them.

Chrome 86 on Android 10

**Comment by Eiim** [comment] 2020-10-25 17:53
Note: I came from https://openingh.openstreetmap.de/evaluation_tool/, which cites this repo for both the library and website, however, I'm not 100% certain if the website is actually included in this repo from a look at the readme. If it's not, sorry about that.

**Comment by ypid** [comment] 2020-10-25 18:56
I cannot reproduce this. I also have a Android 10 with Bromite/Chromium 86 and the "value for "opening_hours"" and date fields bring up even the matching (#257) on-screen keyboard.

**Comment by Eiim** [comment] 2020-10-25 19:03
For some reason, I failed to notice that the only fields affected were state and country, which after playing with it on Desktop I now realize are driven by the lat/long fields. It might be nice to mark those boxes slightly differently, as I thought I could input them in lieu of coordinates (my phone currently has an issue preventing me from giving location access to websites), but regardless, this is definitely invalid.

**Comment by ypid** [comment] 2020-10-25 19:29
Right, the state and country fields are driven by the lat/long. I am currently not really the guy for UI/UX stuff. But I will keep this in the back of my mind as I agree with you.

**Comment by KristjanESPERANTO** [comment] 2020-11-07 17:14
I think a different look of the read-only fields would solve this. I created a PR. What do you think?

**Comment by ypid** [comment] 2020-11-07 18:13
Thank you! This issue is closed by your PR that I just merged and deployed, #349.

**Closed by ypid** 2020-11-07 18:13 UTC
Labels: impact/browser, type/enhancement
