### ISSUE TITLE
Parsing fails with colon after day of week

### ISSUE THREAD

**Issue by edewaele** [opening-hours/opening_hours.js#244] opened 2017-11-22 20:47 UTC
Hi,

The following string `Mo-We: 10:00-19:00, Th-Fr: 10:00-20:00, Sa: 9:00-18:00, Su: 11:00-18:00` makes the parser panic with this mysterious error `TypeError: Cannot read property '0' of undefined`. This is due to the colons after the weekdays, and only one colon is enough to reproduce.

[Example with the evaluation tool](https://openingh.ypid.de/evaluation_tool/?EXP=Mo-We%2010%3A00-19%3A00%2C%20Th-Fr%2010%3A00-20%3A00%2C%20Sa%209%3A00-18%3A00%2C%20Su%3A%2011%3A00-18%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1511379000000)

**Comment by ypid** [comment] 2017-11-23 17:59
The root issue is the `,` see #86. Also note that `;` is preferred for your oh value:

```
Mo-We 10:00-19:00; Th-Fr 10:00-20:00; Sa 09:00-18:00; Su 11:00-18:00
```

Feel free to close this issue. It is basically a duplicate of #86.

**Closed** 2017-11-23 20:06 UTC
Labels: type/bug, type/duplicate
