### ISSUE TITLE
Make input tolerance language aware.

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#107] opened 2015-09-10 21:56 UTC
On "French Page": 
Example: http://openingh.openstreetmap.de/evaluation_tool/?EXP=Lu-Di%2012%3A00-15%3A00%2C18%3A30-23%3A00&DATE=1441921920000&lat=48.7769&lon=9.1844&mode=0
"Di" must be detected on french page as dimanche not as Dienstag.

**Comment by dex2000** [comment] 2015-09-10 21:59
Edit: Oops, the permalink dont adds "setlang". (Another Bug?) Open the Link and click on French (or some other language)

**Comment by ypid** [comment] 2015-09-11 07:37
> Edit: Oops, the permalink dont adds "setlang".

That is not a bug, it’s a feature! :smile: I am pretty sure that when you are sharing a permalink and have set the language lets say to German and someone else opens it up he/she will want the previously used language (which is saved via cookies).

> "Di" must be detected on french page as dimanche not as Dienstag.

You are right, the entire input tolerance is not language aware. This will add another peace of complexity to the core …

This feature would require to detect the language of the oh value and I guess that is the trickiest part. I am not yet sure how to solve this the best way. I guess tagging wrong words with a language and then reevaluating the input tolerance with that language could be done if no language was given to `new opening_hours()`. But the first thing would be to add a new constructor parameter like `input_locale` and skip the detection for now.

Could be done …

**Comment by ypid** [comment] 2017-03-10 22:30
Closing as duplicate of #122.

> I think the current implementation is kinda hacky and it would be indeed better to retrieve the localizations from moment.js and let the user optionally decide, which language opening_hours.js is currently parsing (to avoid clashes, if there are any).

**Closed by ypid** 2017-03-10 22:30 UTC
Labels: prio/low, type/enhancement
