### ISSUE TITLE
NLG features from OH rules

### ISSUE THREAD

**Issue by JulianNacci** [opening-hours/opening_hours.js#342] opened 2020-09-07 14:50 UTC
## Question : 
Are there any NLG features in this library (or other know libraries that I gave not found yet) to generate human readable sentences from OH rules ?

In example, consider following rule `Th[2,3] 15:30-18:30` Like : _"Open on each 2nd and 3rd Thursday of the month from 15:30 to 18:30"_ ?

Thanks in advance for your answer,
Julian

**Comment by ypid** [comment] 2020-09-07 16:27
I have a pretty good overview of the existing libraries and none of them supports NLG to my knowledge. This is also not planned for this library currently so I am closing the issue. It might be reconsidered in the future but for now, I think the time table, the current state of a facility and when the state next changes are more useful to users.

What is your use case?

**Comment by JulianNacci** [comment] 2020-09-07 17:03
Thanks for quick answer ! We develop various software for local government and our use case is following : we are using the library both to display facilities states (no issue here) and to manage and display waste collection (pickup) calendar and service to citizens.

You can have a look here for the citizen side / product : https://www.publidata.io/widget-info-dechets (in french)

In this last use-case local government ofte, come to us asking to provide both dynamic calendars and general human readable rules about their services so end user can figure out _"Ok they come each Monday from 5:00 to 12:00 every 2 weeks"_ or _"This service is only available from 15th november to 15th february"_.

All this information is stored in OH rules but we would like to build text from it so it can be displayed / printed / used by chatbots or TTS.

**Comment by ypid** [comment] 2020-09-07 18:55
Thanks for explaining. Nice use case, so I am open to this. Feel free to implement it. The prettify feature should be a good start for how this can be done.

**Comment by ypid** [comment] 2020-10-27 20:31
Turns out this is a duplicate of #234. Still thanks for the discussion. But I am afraid, there is no roadmap for this feature, so somebody will need to speak up.

**Closed by ypid** 2020-10-27 20:31 UTC
Labels: type/duplicate
